### ISSUE TITLE
Bug: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by gugugu9527** [nonebot/nonebot2#257] opened 2021-03-03 11:13 UTC
**描述问题：**

Traceback (most recent call last):
  File "bot.py", line 18, in <module>
    nonebot.init()
  File "...\lib\site-packages\nonebot\__init__.py", line 175, in init
    env = Env()
  File "...\lib\site-packages\nonebot\config.py", line 38, in __init__
    __pydantic_self__).__init__(**__pydantic_self__._build_values(
  File "...\lib\site-packages\nonebot\config.py", line 53, in _build_values
    return deep_update(self._build_secrets_files(_secrets_dir),
TypeError: 'NoneType' object is not callable

**如何复现？**

按照文档上的，安装脚手架
然后运行脚手架里面的bot.py就报错了

**期望的结果**

正常运行

**环境信息：**

 - OS: windows ltsc
 - Python Version: 3.8.8
 - Nonebot Version: v2.0.0a10

**Comment by yanyongyu** [comment] 2021-03-03 11:23
duplicate of #256

**Closed** 2021-03-03 11:24 UTC
Labels: duplicate
